### ISSUE TITLE
To fix

### ISSUE THREAD

**Issue by msberends** [certe-medical-epidemiology/certeplot2#13]

**Comment by msberends** [comment]
- [x] datalabels percentages when y.percent = TRUE
- [x] plot2_add: remove x or y if other var is 1 unique value
- [x] title if empty: y per x, category, facet
- [x] months numeric -> x.character = TRUE

**Comment by erwinhassing** [comment]
- [x] x.expand in combination with x.limits without cutting columns
- [ ] MICs on x-axis
- [x] NA in category/facet
- [x] caption with breaks
